/**
 * Whiskmate\'s Recipes
 * # Introduction  Whiskmate\'s Recipes is a service providing access to a bunch of lovely recipes that will please you on any season. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: kitchen@marmicode.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RecipeRequest { 
    name: string;
}

