/**
 * Recipe
 * ...
 *
 * The version of the OpenAPI document: 1.0
 * Contact: kitchen@marmicode.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ingredient } from './ingredient';


export interface RecipeRequest { 
    /**
     * Recipe\'s name
     */
    name: string;
    ingredients?: Array<Ingredient>;
}

