/**
 * Recipe
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: kitchen@marmicode.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ingredient } from './ingredient';
import { RecipeRequest } from './recipe-request';
import { RecipeAllOf } from './recipe-all-of';


export interface Recipe { 
    id: string;
    created_at: string;
    /**
     * Recipe\'s name
     */
    name: string;
    ingredients: Array<Ingredient>;
}

